# Generated by Django 3.0.4 on 2021-08-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210811_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
